### ISSUE TITLE
[PROPOSAL] Specification for defining which subsystems, components and functionality is implemented in the microscope hardware

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#40]
Each microscope model should define which subsystems (e.g. ion beam, manipualtor) is installed and available, and what functionality is available (e.g. manipulator rotation, plasma gas). Once defined this info can be used to determine how to execute functions, and prevent the API from trying to access undefined resources.

system.yaml:
```yaml
system:
    ip_address: "localhost"
    manufacturer: "Thermo"
    model: "Helios"
```

Helios.yaml:
```yaml

ion: 
    enabled: True
    plasma: True
electron: 
    enabled: True
manipulator: 
    enabled: True
....

```
