### ISSUE TITLE
[BUG] Stage / Shuttle parameters are incorrectly applied

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#96]
Need to update the stage/shuttle pre-tilt parameters as they are currently not applied as expected.

**Desired**
```yaml
stage:
    rotation_flat_to_electron: 49 # degrees                  # (the rotation angle of the stage, when flat to the electron beam)
    rotation_flat_to_ion: 229 # degrees                        # (the rotation angle of the stage, when flat to the ion beam)
    tilt_flat_to_electron: 0 # degrees (pre-tilt)               # (the tilt angle of the electron beam)
    tilt_flat_to_ion: 52 # degrees                                   # (the tilt angle of the ion beam)
    pre_tilt: 35                                                               # (the shuttle pre-tilt)
```
